//
// Created by jasper on 27/02/2020.
//

#ifndef PROJECTSOFTWAREENGINEERING_LIBRARY_H
#define PROJECTSOFTWAREENGINEERING_LIBRARY_H

#include <string>

using namespace std;

#endif //PROJECTSOFTWAREENGINEERING_LIBRARY_H
